# Data parameters
data_folder: "/scratch/mk_cas/full_silva_dataset/sequences/"
alignment_length: 50000

# Taxonomy parameters
taxonomic_level: "Domain"
taxonomic_group: "Bacteria"
classification_level: "Species"
minimum_samples_per_group: 8
fraction_of_sequences_to_use: 0.8

# Hyperparameters
lr: [0.001]
n_epoch: [200]
batch_size: [32]
model: [ConvVAE]
pretrained_model: "results/Bacteria_Species_min_10_ConvVAE_bs_32_lr_0.001_ne_50/final_model.pt"